name: Hello GitHub Actions

on:
  push:
    branches:
      - master

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Exibir mensagem no log
        run: echo "✅ GitHub Actions funcionando com sucesso!"
